name: Build and Conditionally Publish

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm clean-install
      - run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - run: npm clean-install
        # Use "-u" to ignore snapshot mis-matches. Sites may occasionally return different values over time or depending on requester specific details like geographical location. When making changes it's useful to see snapshot differences but we don't really want the CI to fail when there are differences given that our Zod schema passing ensures the ultimate response from media-finder is valid.
      - run: npm run test -- -u

  release:
    name: Publish Package
    if: (github.event_name == 'push') && (github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    needs: [lint, test]
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm clean-install

      - name: Build
        run: npm run build

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
